### ISSUE TITLE
 advanced application root?

### ISSUE THREAD

**Issue by vc7deo** [blacksmoke26/yii2cdn#3]
1) for the advanced application root is the frontend/web ??

2) how to add images to the cdn??

**Comment by blacksmoke26** [comment]
sorry for not giving reply at the time. 

1) for the advanced application root is the frontend/web ??

> Yes! each app can be configured with different cdn settings.

2) how to add images to the cdn??

> Sorry, Can you explain?

**Comment by vc7deo** [comment]
1)advance application structure is different right 
so we create cdn folder inside frontend or outside of it? 

2)can we manage images load from cdn directory?  or just css and js only?

**Comment by blacksmoke26** [comment]
1) Yes we can setup different CDN component for each application;
1. `/backend/config/config.php`
2. `/frontend/config/config.php`

2) For now, `css` and `js` only

> You can leave well explained details here about how you want to load images from that. If it's worthy, I will do it.

**Comment by vc7deo** [comment]
Thanks @blacksmoke26 for your quick and prompt response

for images..i want to load background images ..etc added in the css files.according to your above comment we can load css and js.so just load images called in the css files

secondly suppose i upload images in uploads folder and load that image also through cdn.priority is the first point

**Comment by blacksmoke26** [comment]
First of all, Thank you! I will think about that, seems interesting!

> BTW, You can fork the repository, will appreciate your help! I have tons of features (in my mind) to do but lack of time due to on going project! That component was also a part of my current project.
