### ISSUE TITLE
Undefined index: componentId,

### ISSUE THREAD

**Issue by dbd5** [blacksmoke26/yii2cdn#4]
Hi,

Great extension!
Seems there's a small typo here, could you remove the comma?
...
Section.php 
$this->componentId = $config['componentId,'];

**Comment by blacksmoke26** [comment]
First of All, Thank you for your great efforts.

Will fix it ASAP.

**Comment by blacksmoke26** [comment]
Bug fixed:
https://github.com/blacksmoke26/yii2cdn/blob/master/src/Section.php
