### ISSUE TITLE
Wrong reference to style sheet

### ISSUE THREAD

**Issue by dbd5** [blacksmoke26/yii2cdn#5]
Hi,

After setup with Yii2 Advanced template, the generated reference to the stylesheet is as follows
`<link href="style.css" rel="stylesheet">`

I expected `<link href="css/style.css" rel="stylesheet">`
This of course is a local setup on Vagrant, how can I resolve this?

Thank you

**Comment by blacksmoke26** [comment]
Thank you for using Yii2cdn.

Can you please provide more details as well as page link, Code or CDN-Config section source?

You can chat via Gitter for further details:
https://gitter.im/blacksmoke26/yii2

**Comment by dbd5** [comment]
Hi @blacksmoke26 ,
I think this is no longer relevant, I will close and open a couple of relevant issues -- sorry for the delay, been busy with work
