### ISSUE TITLE
Undefined index: @sectionsAttrs

### ISSUE THREAD

**Issue by dbd5** [blacksmoke26/yii2cdn#6]
Hi @blacksmoke26 ,

It seems there's a small bug in ConfigParser (line 377)

` if ( !count($compAttrs['@sectionsAttrs']) ) {
            return [];
        }`
       
I've been able to proceed with the following work around;

`if (!isset($compAttrs['@sectionsAttrs']) || !count($compAttrs['@sectionsAttrs']) ) {
            return [];
		}`

**Comment by blacksmoke26** [comment]
Will merge. Thanks!

**Comment by blacksmoke26** [comment]
Fixed
