### ISSUE TITLE
How does online/offline work?

### ISSUE THREAD

**Issue by gb5256** [blacksmoke26/yii2cdn#9]
Hi,
I am struggeling to understand how your component determins if to use the offline files or the online files?
Can you give an example?

Thanks,
gb5256

**Comment by blacksmoke26** [comment]
Hello @gb5256 !

Did you check Wiki?

https://github.com/blacksmoke26/yii2cdn/wiki/Force-using-offline-files
https://github.com/blacksmoke26/yii2cdn/wiki/Offline-mode-usage

**Comment by gb5256** [comment]
Thanks. That makes it clear.
